# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IMDB Assignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IMDB Assignment

  pod 'DropDown'
  pod 'IQKeyboardManagerSwift'
  pod 'NVActivityIndicatorView'
  pod 'SDWebImage', '~> 5.0'

end
